GCP_PROJECT: "edmformer-project"
REGION: "us-central1"
BUCKET_NAME: "edmformer-data"
ARTIFACT_REPO: "edmformer-repo"
PIPELINE_ROOT: "gs://edmformer-data/pipeline-root"
SERVICE_ACCOUNT_EMAIL: "service-578269942187@gcp-sa-aiplatform.iam.gserviceaccount.com"

LABELS_JSONL_GCS: "gs://edmformer-data/metadata/dataset.jsonl"
SPLIT_IDS_GCS: "gs://edmformer-data/metadata/split_ids.txt"
EVAL_SPLIT_IDS_GCS: "gs://edmformer-data/metadata/split_ids_val.txt"
EMBEDDINGS_GCS_DIR: "gs://edmformer-data/embeddings"
CHECKPOINT_DIR_GCS: "gs://edmformer-data/checkpoints/edmformer-run1"
EMBEDDING_SUBDIRS: "musicfm_30s,muq_30s,musicfm_420s,muq_420s"
