GCP_PROJECT: "edmformer-project"
REGION: "us-central1"
BUCKET_NAME: "edmformer-data"
ARTIFACT_REPO: "edmformer-repo"
PIPELINE_ROOT: "gs://edmformer-data/pipeline-root"
SERVICE_ACCOUNT_EMAIL: "service-578269942187@gcp-sa-aiplatform.iam.gserviceaccount.com"

LABELS_JSONL_GCS: "gs://edmformer-data/metadata/dataset.jsonl"
SPLIT_IDS_GCS: "gs://edmformer-data/metadata/split_ids.txt"
EMBEDDINGS_GCS_DIR: "gs://edmformer-data/embeddings"
